version: '3.7'

services:
  mongo1:
    image: mongo:8
    ports:
      - 127.0.10.1:27017:27017
    volumes:
      - mongo1:/data/db
    restart: unless-stopped
    command: "--wiredTigerCacheSizeGB 0.25 --replSet rs0"

  mongo2:
    image: mongo:8
    ports:
      - 127.0.10.2:27017:27017
    volumes:
      - mongo2:/data/db
    restart: unless-stopped
    command: "--wiredTigerCacheSizeGB 0.25 --replSet rs0"

  mongo3:
    image: mongo:8
    ports:
      - 127.0.10.3:27017:27017
    volumes:
      - mongo3:/data/db
    restart: unless-stopped
    command: "--wiredTigerCacheSizeGB 0.25 --replSet rs0"
volumes:
  mongo1:
  mongo2:
  mongo3: